### PR TITLE
remove superfluous "command" and slightly linearize

### PR DESCRIPTION
**Pull request by port19x**
Hi,

you have some very rough edges in your install scripts.
I smoothed out the lowest hanging fruits, but I suggest you go in yourself and clean up further after a merge.

### CODE REVIEW

**Comment by port19x** [comment]
@tale (github doesn't always notify on open PRs)

**Comment by tale** [comment]
Hey thank you for the help, I'm actually in the middle of migrating away from this bootstrap script to a new one since I switched to Nix recently.

**Comment by port19x** [comment]
Ah, in that case this PR doesn't make much sense.
Nix is a nice system

**Comment by tale** [comment]
It is, thank you for the help though, feel free to look at the setup script once I push that, I'll notify you here if you're interested!

**Pull request closed without merging**
